version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: 
        - name: Install
        - command: npm install
      - run: 
        - name: Test
        -command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test