version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm lint
workflows:
  version: 2
  build_and_test:
    jobs:
      - test